version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '%(asctime)s:%(name)s:%(module)s:%(funcName)s:%(lineno)d:%(levelname)s:%(message)s'
  console:
    format: '[%(asctime)s] (%(name)s:%(funcName)s:%(lineno)d:%(levelname)s) %(message)s'
    datefmt: "%Y-%m-%d %H:%M:%S"
  email:
    format: '[%(levelname)-8s] %(message)s'
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console
    stream: ext://sys.stdout
  main:
    () : __main__.logpath
    level: DEBUG   
    formatter: default

loggers:
  monitor:
    level: DEBUG
    handlers: [console, main]
    propagate: true
  config:
    level: DEBUG
    handlers: [console, main]
    propagate: true
  tools:
    level: DEBUG
    handlers: [console, main]
    propagate: true
  find:
    level: DEBUG
    handlers: [console, main]
    propagate: true
  git:
    level: DEBUG
    handlers: [console, main]
    propagate: true
  qsub:
    level: DEBUG
    handlers: [console, main]
    propagate: true
